matrix:
    include:
        - os: linux
          env:
              - PROJECT=fretwork
              - ARCH=i686
              - MINGW=w64
              - WIN=win32
              - PLATFORM="${ARCH}-${MINGW}-mingw32"
        #- os: linux
        #  env:
        #      - PROJECT=fretwork
        #      - ARCH=x86_64
        #      - MINGW=w64
        #      - WIN=win64
        #      - PLATFORM="${ARCH}-${MINGW}-mingw32"

install:
    - sudo apt-get install -y
        mingw-w64
        mingw-w64-tools
        gcc-mingw-w64

script:
    - source fretwork-deps.sh
    - build_workspace
    - build_iconv
    - build_zlib
    - build_glib
    - build_pkgconfig
    - build_libogg
    - build_libtheora
    - build_libvorbis
    - build_soundtouch
    - build_sdl_mixer

    - package_dist

deploy:
    provider: releases
    api_key:
        secure: tc39cVMtVMHG8vU5R2KeFeXqMqkKReLJzIaG76Xl14U3Yg6aeYN/tNwmGRtMqIo//W3mckOkJWEs0A/cGCxyJWmYT6UzjrONcRgnECfG+wUrcUyKX4FHDH/hFH9XeWUNPGg86lc1Q10jOrbOxowIfaKAGoenZylv6EDZ/9Zzc8ZfP+K5/ettmjFUXnKAz0zXE1osD7BDq8zGroiZzN0vkIbXHjFPV/joOWuzsvL9Ylb8IUgBScSLFqZK5hgRdrXT9bv9iIj15P/KQCHvzlS9x3/sHTSENd8JKfCaYxlFNY1V2BGgzswSxF4S0ONEGeO2XJvICQowG06ZR1xJ1Y5BDWMttbjcJ+ehTBll81phT61dlQCIMk7BZ3qCitbFvv0eI1fPpQLZRi3GiBqQuuQZjqhrxmyCb18hPqStE9EdTTi7E4bsvVQavy+RqOxL7SbsTUZ/bNaV9MqtjrsrXCnh8v/C+tt5IYR6aurDU/jvAb3/vrLfmbdvIavmFN/gfVDJvnXoQoKsT0Y3OC4vCXf08sFyw/u8NGVe7myEXsa2OV8apUc9jPWi8jIaF8at7cWZYySR9n0JXG6a9/nuTSc/jc2FGTPfoVecFOW0rYhrXoArY5RfAlTwyYJ4T5ff7lapQUdcu+GAjwORC2ii+DSlvfI2oe1WHGmmYiC7V+yYLyE=
    file_glob: true
    file: out/*
    skip_cleanup: true
    draft: true
    on:
        repo: fofix/win-dependencies
